INSERT INTO ARENA (NomeArena, Citta) VALUES
('State Farm Arena', 'Atlanta'),
('TD Garden', 'Boston'),
('Barclays Center', 'Brooklyn'),
('Spectrum Center', 'Charlotte'),
('United Center', 'Chicago'),
('Rocket Mortgage FieldHouse', 'Cleveland'),
('American Airlines Center', 'Dallas'),
('Ball Arena', 'Denver'),
('Little Caesars Arena', 'Detroit'),
('Chase Center', 'San Francisco'),
('Toyota Center', 'Houston'),
('Gainbridge Fieldhouse', 'Indianapolis'),
('Intuit Dome', 'Inglewood'),
('Crypto.com Arena', 'Los Angeles'),
('FedExForum', 'Memphis'),
('Kaseya Center', 'Miami'),
('Fiserv Forum', 'Milwaukee'),
('Target Center', 'Minneapolis'),
('Smoothie King Center', 'New Orleans'),
('Madison Square Garden', 'New York'),
('Paycom Center', 'Oklahoma City'),
('Kia Center', 'Orlando'),
('Wells Fargo Center', 'Philadelphia'),
('Footprint Center', 'Phoenix'),
('Moda Center', 'Portland'),
('Golden 1 Center', 'Sacramento'),
('Frost Bank Center', 'San Antonio'),
('Scotiabank Arena', 'Toronto'),
('Delta Center', 'Salt Lake City'),
('Capital One Arena', 'Washington');