INSERT INTO SQUADRA (Nome_Squadra, Citta, Nome_Arena, ID_Allenatore) VALUES
('Hawks', 'Atlanta', 'State Farm Arena', 101),
('Celtics', 'Boston', 'TD Garden', 102),
('Nets', 'Brooklyn', 'Barclays Center', 103),
('Hornets', 'Charlotte', 'Spectrum Center', 104),
('Bulls', 'Chicago', 'United Center', 105),
('Cavaliers', 'Cleveland', 'Rocket Mortgage FieldHouse', 106),
('Mavericks', 'Dallas', 'American Airlines Center', 107),
('Nuggets', 'Denver', 'Ball Arena', 108),
('Pistons', 'Detroit', 'Little Caesars Arena', 109),
('Warriors', 'San Francisco', 'Chase Center', 110),
('Rockets', 'Houston', 'Toyota Center', 111),
('Pacers', 'Indianapolis', 'Gainbridge Fieldhouse', 112),
('Clippers', 'Inglewood', 'Intuit Dome', 113),
('Lakers', 'Los Angeles', 'Crypto.com Arena', 114),
('Grizzlies', 'Memphis', 'FedExForum', 115),
('Heat', 'Miami', 'Kaseya Center', 116),
('Bucks', 'Milwaukee', 'Fiserv Forum', 117),
('Timberwolves', 'Minneapolis', 'Target Center', 118),
('Pelicans', 'New Orleans', 'Smoothie King Center', 119),
('Kings', 'Sacramento', 'Golden 1 Center', 120),
('Thunder', 'Oklahoma City', 'Paycom Center', 121),
('Magic', 'Orlando', 'Kia Center', 122),
('76ers', 'Philadelphia', 'Wells Fargo Center', 123),
('Trail Blazers', 'Portland', 'Moda Center', 124),
('Suns', 'Phoenix', 'Footprint Center', 125),
('Spurs', 'San Antonio', 'Frost Bank Center', 126),
('Knicks', 'New York', 'Madison Square Garden', 127),
('Raptors', 'Toronto', 'Scotiabank Arena', 128),
('Jazz', 'Salt Lake City', 'Delta Center', 129),
('Wizards', 'Washington', 'Capital One Arena', 130);