INSERT INTO SQUADRA (Nome_Squadra, Citta, Nome_Arena, ID_Allenatore) VALUES
('Hawks', 'Atlanta', 'State Farm Arena', 154),
('Celtics', 'Boston', 'TD Garden', 289),
('Nets', 'Brooklyn', 'Barclays Center', 341),
('Hornets', 'Charlotte', 'Spectrum Center', 412),
('Bulls', 'Chicago', 'United Center', 498),
('Cavaliers', 'Cleveland', 'Rocket Mortgage FieldHouse', 515),
('Mavericks', 'Dallas', 'American Airlines Center', 577),
('Nuggets', 'Denver', 'Ball Arena', 621),
('Pistons', 'Detroit', 'Little Caesars Arena', 688),
('Warriors', 'San Francisco', 'Chase Center', 705),
('Rockets', 'Houston', 'Toyota Center', 733),
('Pacers', 'Indianapolis', 'Gainbridge Fieldhouse', 790),
('Clippers', 'Inglewood', 'Intuit Dome', 812),
('Lakers', 'Los Angeles', 'Crypto.com Arena', 845),
('Grizzlies', 'Memphis', 'FedExForum', 876),
('Heat', 'Miami', 'Kaseya Center', 899),
('Bucks', 'Milwaukee', 'Fiserv Forum', 910),
('Timberwolves', 'Minneapolis', 'Target Center', 933),
('Pelicans', 'New Orleans', 'Smoothie King Center', 944),
('Knicks', 'New York', 'Madison Square Garden', 678),
('Thunder', 'Oklahoma City', 'Paycom Center', 123),
('Magic', 'Orlando', 'Kia Center', 167),
('76ers', 'Philadelphia', 'Wells Fargo Center', 234),
('Suns', 'Phoenix', 'Footprint Center', 456),
('Trail Blazers', 'Portland', 'Moda Center', 345),
('Kings', 'Sacramento', 'Golden 1 Center', 955),
('Spurs', 'San Antonio', 'Frost Bank Center', 567),
('Raptors', 'Toronto', 'Scotiabank Arena', 789),
('Jazz', 'Salt Lake City', 'Delta Center', 801),
('Wizards', 'Washington', 'Capital One Arena', 902);