--TESSERATO
CREATE TABLE TESSERATO (
    ID SERIAL PRIMARY KEY,
    Nome VARCHAR(50) NOT NULL,
    Cognome VARCHAR(50) NOT NULL
);

--ARENA
CREATE TABLE ARENA (
    NomeArena VARCHAR(100) PRIMARY KEY,
    Citta VARCHAR(50) NOT NULL
);

--ALLENATORE
CREATE TABLE ALLENATORE (
    ID INT PRIMARY KEY,
    Anni_Esperienza INT DEFAULT 0 CHECK (Anni_Esperienza >= 0),
    CONSTRAINT FK_Allenatore_Tesserato FOREIGN KEY (ID) REFERENCES TESSERATO(ID) ON DELETE CASCADE
);

--ARBITRO
CREATE TABLE ARBITRO (
    ID INT PRIMARY KEY,
    Ruolo VARCHAR(20) CHECK (Ruolo IN ('TAVOLO', 'REPLAY', 'CAMPO')),
    Anni_Esperienza INT DEFAULT 0 CHECK (Anni_Esperienza >= 0),
    CONSTRAINT FK_Arbitro_Tesserato FOREIGN KEY (ID) REFERENCES TESSERATO(ID) ON DELETE CASCADE
);

--SQUADRA
CREATE TABLE SQUADRA (
    Nome_Squadra VARCHAR(50) PRIMARY KEY,
    Citta VARCHAR(50) NOT NULL,
    Nome_Arena VARCHAR(100) NOT NULL,
    ID_Allenatore INT UNIQUE NOT NULL,
    CONSTRAINT FK_Squadra_Arena FOREIGN KEY (Nome_Arena) REFERENCES ARENA(NomeArena),
    CONSTRAINT FK_Squadra_Allenatore FOREIGN KEY (ID_Allenatore) REFERENCES ALLENATORE(ID)
);

--GIOCATORE
CREATE TABLE GIOCATORE (
    ID INT PRIMARY KEY,
    Ruolo VARCHAR(10) NOT NULL CHECK (Ruolo IN ('Ala', 'Guardia', 'Pivot')),
    PPG DECIMAL(5,2) DEFAULT 0.00,
    Altezza INT NOT NULL CHECK (Altezza BETWEEN 150 AND 250),
    Peso INT NOT NULL CHECK (Peso BETWEEN 50 AND 200),
    Nome_Squadra VARCHAR(50) NOT NULL,
    CONSTRAINT FK_Giocatore_Tesserato FOREIGN KEY (ID) REFERENCES TESSERATO(ID) ON DELETE CASCADE,
    CONSTRAINT FK_Giocatore_Squadra FOREIGN KEY (Nome_Squadra) REFERENCES SQUADRA(Nome_Squadra)
);

--PARTITA
CREATE TABLE PARTITA (
    IDPartita SERIAL PRIMARY KEY,
    DataOra TIMESTAMP NOT NULL,
    SqCasa VARCHAR(50) NOT NULL,
    SqOspite VARCHAR(50) NOT NULL,
    Nome_Arena VARCHAR(100) NOT NULL,
    CONSTRAINT FK_Partita_SqCasa FOREIGN KEY (SqCasa) REFERENCES SQUADRA(Nome_Squadra),
    CONSTRAINT FK_Partita_SqOspite FOREIGN KEY (SqOspite) REFERENCES SQUADRA(Nome_Squadra),
    CONSTRAINT FK_Partita_Arena FOREIGN KEY (Nome_Arena) REFERENCES ARENA(NomeArena),
    CONSTRAINT CHK_SquadreDiverse CHECK (SqCasa <> SqOspite)
);

--DIREZIONE
CREATE TABLE DIREZIONE (
    ID_Partita INT,
    ID_Arbitro INT,
    PRIMARY KEY (ID_Partita, ID_Arbitro),
    CONSTRAINT FK_Direzione_Partita FOREIGN KEY (ID_Partita) REFERENCES PARTITA(IDPartita) ON DELETE CASCADE,
    CONSTRAINT FK_Direzione_Arbitro FOREIGN KEY (ID_Arbitro) REFERENCES ARBITRO(ID) ON DELETE CASCADE
);

--PRESTAZIONE
CREATE TABLE PRESTAZIONE (
    ID_Giocatore INT,
    ID_Partita INT,
    Pt_Segnati INT DEFAULT 0 CHECK (Pt_Segnati >= 0),
    Assist INT DEFAULT 0 CHECK (Assist >= 0),
    Min_Giocati INT DEFAULT 0 CHECK (Min_Giocati >= 0 AND Min_Giocati <= 60),
    Falli INT DEFAULT 0 CHECK (Falli >= 0 AND Falli <= 6),
    PRIMARY KEY (ID_Giocatore, ID_Partita),
    CONSTRAINT FK_Prest_Giocatore FOREIGN KEY (ID_Giocatore) REFERENCES GIOCATORE(ID) ON DELETE CASCADE,
    CONSTRAINT FK_Prest_Partita FOREIGN KEY (ID_Partita) REFERENCES PARTITA(IDPartita) ON DELETE CASCADE
);